# baseurl: /slideshow # the subpath of your site, e.g. /blog
#url: "http://a1ip.github.io" # the base hostname & protocol for your site
title: Christian slideshow
description: Christian slideshow powered by Unsplash Source API
#slides: 5
#delay: 30 # animation time in seconds

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
